### ISSUE TITLE
explicit functions for default jump motions

### ISSUE THREAD

**Issue by wbolster** [PythonNut/evil-easymotion#35]
would you consider a pr that changes all the default motions to be explicitly defined and named (and autoloaded) instead of defining them while immediately assigning a key binding?

the reason i'm asking is that it's currently impossible to use remapped navigation keys when using a colemak keyboard layout (https://github.com/wbolster/evil-colemak-basics), without copying most of the implementation of evil-easymotion into my own `init.el`. if instead this package had `evil-easy-motion-jump-previous-line` functions (and a lot more), i could simply build my own key bindings to invoke those jumps.

**Comment by PythonNut** [comment]
Oh my goodness, I totally forgot about this! So sorry.

Indeed, I'm not entirely happy with my current keybinding setup. The reason I don't define the functions and then bind them later on in `evil-easymotion` is due to an uncomfortable hack that allows me to guarantee that the function names will never collide, but in return makes their names non-deterministic. (Pretty dumb, I know. I was in a hurry one day, and... it worked for me.)

I'll add an issue for that, since it definitely blocks this one.

**Comment by PythonNut** [comment]
#36 is resolved, so now we can discuss a solution to this issue.

**Comment by wbolster** [comment]
i would like a bunch of autoloaded functions (see initial report) which i can bind myself since the default bindings do not play well with the colemak keyboard layout (for which i use https://github.com/wbolster/evil-colemak-basics).

**Comment by wbolster** [comment]
hey @PythonNut,

i plan to work on this and this is what i have in mind:

* predefine motions for all the common motions that are currently defined on the fly in `evilem-default-keybindigs`.

* all these predefined motions will have explicit, friendly names, such as `evilem-motion-forward-word-begin`.

* `evilem-default-keybindings` will just bind these motions instead of defining the motions on the fly. observable behaviour will be unchanged, so existing setups should keep working.

* while refactoring, introduce a proper keymap for the bindings. this would make it easier to bind to multiple prefixes, or to tweak or augment the defaults a bit.

sounds like a plan?

**Comment by wbolster** [comment]
see #47 for a pr that implement this approach.  feedback welcome!

**Comment by wbolster** [comment]
closed via #47
