### ISSUE TITLE
[BUG] Line properties change in org-mode buffer

### ISSUE THREAD

**Issue by WhatDothLife** [PythonNut/evil-easymotion#61]
When I'm editing an org-mode buffer and my cursor is behind the end of collapsed headings, the line properties change after calling `evilem-motion-next-line`, since the three dots teasing the heading contents move to the line below, creating a new one. I've added two pictures that show the described behavior.

![orgEvilem](https://user-images.githubusercontent.com/33008303/70852711-0628dd80-1ea5-11ea-98ec-60a60b79bfbe.png)
![orgEvilem2](https://user-images.githubusercontent.com/33008303/70852712-088b3780-1ea5-11ea-9f55-87c4a421ed0f.png)

**Comment by WhatDothLife** [comment]
Do you need any additional information? If not, then I'd be glad to see a response.

**Comment by PythonNut** [comment]
I suppose some more information would be handy. I don't use org mode, so I don't have any idea why this would be the case.

Does `evil-next-line` do something similar? `evil-easymotion` really just runs the the command until you reach the edge of the viewable region of the buffer, collects the visited locations, returns the point to the original location, and sends the list of visited points to `avy`, so I'd assume the side-effects are caused by the command being run...
